### ISSUE TITLE
Move ImageFiltering.jl examples to JuliaImages demo section

### ISSUE THREAD

**Issue by ashwani-rathee** [JuliaImages/juliaimages.github.io#256]
ImageFiltering.jl website has three demos 
- Custom median filters
- Median/Mean filters
- Template Matching

could be moved to main websites demo section

**Comment by johnnychen94** [comment]
I like the idea of getting all demos in one place. But it turns out to be a maintenance burden when source codes are in one repo and the documentation(including demos) in the other.

It would be appreciated if there's a syncing tool to get the documentation from, e.g. automatically, ImageFiltering, ImageMorphology, and then build the centralized version here.

**Comment by ashwani-rathee** [comment]
Intending to use MultiDocumenter for this, soon!
