### ISSUE TITLE
stable badge in readme

### ISSUE THREAD

**Issue by waldyrious** [JuliaImages/juliaimages.github.io#4]
Why was the "stable" badge removed from the readme in d22ffcc? It shows up in http://juliaimages.github.io along with the "latest" badge.

By the way, the link above should probably be added to the repository description.

**Comment by timholy** [comment]
At the time, the stable link gave a 404 error. Now, it's been long enough since I read about this stuff that I don't even remember the difference between the two. One thing to keep in mind is that these docs aren't tied to a single package, they're for the whole ecosystem of packages, each of which can have a separate release schedule.

**Comment by waldyrious** [comment]
Fixed in #13
